In [2]:
from tokenizer import Tokenizer
import torch
import torch.nn as nn
import torch.nn as nn
from torch.nn import functional as f
torch.manual_seed(42)

In [3]:
obj = Tokenizer()
obj.character_tokenizer()
data=torch.tensor(obj.encoder(s=obj.data),dtype=torch.int64)

In [4]:
obj.vocab_size

106

In [5]:
n=int(0.7*len(data))
traindata = data[:n]
intrimdata = data[n:]

In [6]:
block_size = 8  # context length
batch_size = 4   # number of sequences in a batch
def getbatch_train_data():
    data = torch.tensor(traindata) 
    ix = torch.randint(len(data) - block_size, (batch_size,))
    x = torch.stack([data[i:i+block_size] for i in ix])
    y = torch.stack([data[i+1:i+block_size+1] for i in ix])
    return x,y

def getbatch_test_data():
    data = torch.tensor(intrimdata) 
    ix = torch.randint(len(data) - block_size, (batch_size,))
    x = torch.stack([data[i:i+block_size] for i in ix])
    y = torch.stack([data[i+1:i+block_size+1] for i in ix])
    return x,y

In [7]:
class BigramLanguagemodel(nn.Module):
    def __init__(self, vocab_size):
        super().__init__()
        self.token_embedding = nn.Embedding(embedding_dim=vocab_size,num_embeddings=vocab_size)

    def forward(self,idx,targets=None):
        logits = self.token_embedding(idx)
        if  targets != None:
            B,T,C = logits.shape
            logits = logits.view(B*T,C)
            targets = targets.view(B*T)
            loss = f.cross_entropy(logits,target=targets)
            
        else:
            loss=None
        return logits,loss
    
    def generate(self, idx, max_newtokens):
        for i in range(max_newtokens):
            logits, _= self(idx)
            logits = logits[:,-1,:]
            probs = f.softmax(logits,dim=1)
            id_next = torch.multinomial(probs,num_samples=1)
            idx = torch.cat((idx, id_next), dim=1)
        return idx
    
otg=BigramLanguagemodel(vocab_size=obj.vocab_size)


In [8]:
optimizer = torch.optim.AdamW(otg.parameters(),lr=1e-2)

In [9]:
eval_iters=200
@torch.no_grad()
def estimate_loss():
    out={}
    otg.eval()
    for split in [getbatch_train_data,getbatch_test_data]:
        losses = torch.zeros(eval_iters)
        for i in range(eval_iters):
            X,Y = split()
            logits,loss = otg(X,Y)
            losses[i] = loss.item()
        out[split] = losses.mean().item()
    otg.train()
    return out

In [10]:
batch_size = 32
for i in range(100):
    if i%10 ==0:
        print(i,'   ',estimate_loss())
    x,y=getbatch_train_data()
    logits,loss=otg.forward(x,y)
    optimizer.zero_grad(set_to_none=True)
    loss.backward()
    optimizer.step()
    # print(loss.item())

C:\Users\ASUS\AppData\Local\Temp\ipykernel_17816\341454980.py:4: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.detach().clone() or sourceTensor.detach().clone().requires_grad_(True), rather than torch.tensor(sourceTensor).
  data = torch.tensor(traindata)
C:\Users\ASUS\AppData\Local\Temp\ipykernel_17816\341454980.py:11: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.detach().clone() or sourceTensor.detach().clone().requires_grad_(True), rather than torch.tensor(sourceTensor).
  data = torch.tensor(intrimdata)


0     {<function getbatch_train_data at 0x000001E207A43CE0>: 5.101233959197998, <function getbatch_test_data at 0x000001E21E5D8540>: 5.107342720031738}
10     {<function getbatch_train_data at 0x000001E207A43CE0>: 4.988953590393066, <function getbatch_test_data at 0x000001E21E5D8540>: 4.985970973968506}
20     {<function getbatch_train_data at 0x000001E207A43CE0>: 4.869590759277344, <function getbatch_test_data at 0x000001E21E5D8540>: 4.8675856590271}
30     {<function getbatch_train_data at 0x000001E207A43CE0>: 4.752744674682617, <function getbatch_test_data at 0x000001E21E5D8540>: 4.744067192077637}
40     {<function getbatch_train_data at 0x000001E207A43CE0>: 4.635580062866211, <function getbatch_test_data at 0x000001E21E5D8540>: 4.631383419036865}
50     {<function getbatch_train_data at 0x000001E207A43CE0>: 4.514193534851074, <function getbatch_test_data at 0x000001E21E5D8540>: 4.5192084312438965}
60     {<function getbatch_train_data at 0x000001E207A43CE0>: 4.411076545715332, <fu

In [11]:
B,T,C=4,8,2
x=torch.randn(B,T,C)
xbow = torch.zeros((B,T,C))
for b in range(B):
    for t in range(T):
        xprev = x[b,:t+1]
        xbow[b,t] = torch.mean(xprev,0)

In [12]:
print(xbow[0])
print(x[0])

tensor([[ 1.3008, -1.8827],
        [ 1.0385, -1.4732],
        [ 0.6995, -1.0964],
        [ 0.2769, -0.9581],
        [ 0.2003, -0.9210],
        [ 0.3127, -0.8043],
        [ 0.3746, -0.4678],
        [ 0.3878, -0.4240]])
tensor([[ 1.3008, -1.8827],
        [ 0.7762, -1.0638],
        [ 0.0216, -0.3427],
        [-0.9912, -0.5430],
        [-0.1060, -0.7729],
        [ 0.8744, -0.2205],
        [ 0.7465,  1.5510],
        [ 0.4803, -0.1176]])


In [ ]:
wei = torch.tril(torch.ones(T,T))
wei = wei / wei.sum(1,keepdim=True)
wei @ x
# torch.allclose() to chech if 2 tensors are the same

tensor([[[ 1.3008, -1.8827],
         [ 1.0385, -1.4732],
         [ 0.6995, -1.0964],
         [ 0.2769, -0.9581],
         [ 0.2003, -0.9210],
         [ 0.3127, -0.8043],
         [ 0.3746, -0.4678],
         [ 0.3878, -0.4240]],

        [[ 0.8055,  2.5337],
         [ 0.2776,  0.8636],
         [ 0.7271,  0.4606],
         [ 0.9032,  0.1101],
         [ 0.6301,  0.0227],
         [ 0.6855,  0.0997],
         [ 0.3775,  0.0715],
         [ 0.3364,  0.1831]],

        [[-0.3858,  0.0551],
         [-0.3464, -0.0734],
         [-0.4115,  0.5100],
         [-0.2598,  0.2630],
         [-0.1920,  0.0705],
         [-0.0336,  0.0503],
         [-0.2428,  0.2146],
         [-0.2896,  0.0305]],

        [[ 0.1899, -1.2821],
         [-0.6500, -0.1692],
         [-0.6587, -0.1071],
         [-0.4394, -0.4488],
         [-0.6596, -0.3917],
         [-0.8698, -0.6156],
         [-0.9608, -0.6004],
         [-1.0290, -0.5999]]])

In [16]:
teril = torch.tril(torch.ones(T,T))
wei = torch.zeros((T,T))
wei = wei.masked_fill(teril==0,float('-inf'))
wei = f.softmax(wei,dim=1)
wei @ x

tensor([[[ 1.3008, -1.8827],
         [ 1.0385, -1.4732],
         [ 0.6995, -1.0964],
         [ 0.2769, -0.9581],
         [ 0.2003, -0.9210],
         [ 0.3127, -0.8043],
         [ 0.3746, -0.4678],
         [ 0.3878, -0.4240]],

        [[ 0.8055,  2.5337],
         [ 0.2776,  0.8636],
         [ 0.7271,  0.4606],
         [ 0.9032,  0.1101],
         [ 0.6301,  0.0227],
         [ 0.6855,  0.0997],
         [ 0.3775,  0.0715],
         [ 0.3364,  0.1831]],

        [[-0.3858,  0.0551],
         [-0.3464, -0.0734],
         [-0.4115,  0.5100],
         [-0.2598,  0.2630],
         [-0.1920,  0.0705],
         [-0.0336,  0.0503],
         [-0.2428,  0.2146],
         [-0.2896,  0.0305]],

        [[ 0.1899, -1.2821],
         [-0.6500, -0.1692],
         [-0.6587, -0.1071],
         [-0.4394, -0.4488],
         [-0.6596, -0.3917],
         [-0.8698, -0.6156],
         [-0.9608, -0.6004],
         [-1.0290, -0.5999]]])